#! /bin/sh
. mp-functions

get_source()
{
  do_get_source
}

do_get_source()
{
  : ${source_package_type:=tar.gz}
  : ${source:=$name-$version.$source_package_type}

  if [ -z "$force" -a -e $sourcedir/$source ]; then
    exit 0
  fi

  if [ -n "$origin" ]; then
    case $origin in
      gnu) pkg_download="http://ftp.gnu.org/pub/gnu/$name/$source";;
      sf) pkg_download="http://downloads.sourceforge.net/sourceforge/$name/$source";;
      *) echo >&2 "$name: Unknown origin."; exit 1;;
    esac
  fi
  
  if [ -n "$download" ]; then
    pkg_download=$download/$source
  fi

  if [ -z "$pkg_download" ]; then
    echo >&2 "$name: download location not found."
    exit 1
  fi

  cd $sourcedir
  echo Downloading $name from $pkg_download ...
  wget -c $pkg_download
}

case $1 in
  -f|--force) force=yes; shift;;
  -*) echo "$0: unrecognized option"; exit 1;;
esac

if [ -z "$1" ]; then
  echo "Usage: $0 package-name ..."
  exit 1
fi
name=$1

. $(get_recipe_name $name)

get_source
