#! /bin/sh
. mp-functions

unpack_source()
{
  : ${source_package_type:=tar.gz}
  : ${source:=$name-$version.$source_package_type}
  : ${top_srcdir:=$name-$version}

  sourcename=$sourcedir/$source

  if [ ! -e $sourcename ]; then
    echo >&2 "Could not find source for $name"
    exit 1
  fi

  buildroot=$builddir/$name-$version-$release
  
  if [ ! -d $buildroot ]; then
    mkdir $buildroot
  fi
  
  cd $buildroot
  
  if [ -d $top_srcdir ]; then
    echo "source already unpacked"
    exit
  fi
  
  tar -zxf $sourcename
  
  if [ $? != 0 ]; then
    echo >&2 "Failed to unpack $sourcename"
    exit 1
  fi
  
  cd ${top_srcdir}
  
  pkg_patchdir=$patchdir/$name
  
  if [ -d $pkg_patchdir ]; then
    find $pkg_patchdir -name '*.patch' -exec patch -p1 -i '{}' \;
  fi
  
  src_prep
  
}

src_prep()
{
  do_prep
}

do_prep()
{
  :
}

if [ -z "$1" ]; then
  echo "Usage: $0 package-name ..."
  exit 1
fi
name=$1

. $(get_recipe_name $name)

unpack_source
