#! /bin/sh

# mpk - top level, user visible script.
# This file is part of Minipack - an automated build tool
#
# Copyright (C) 2008 Cesar Strauss
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

bindir=$(dirname $0)
prog=$(basename $0)
case $bindir in
/*) ;;
*) bindir=$PWD/$bindir;;
esac
mpk=$bindir/$prog
prefix=$(cd $bindir && pwd)
tooldir=$prefix/tools

topdir=$PWD
builddir=$topdir/build
resultdir=$topdir/result
sourcedir=$topdir/sources
recipedir=$prefix/recipes
patchdir=$prefix/patches

export PATH=$tooldir:$resultdir/bin:$PATH

test -f ~/minipack.conf && . ~/minipack.conf
test -f $topdir/minipack.conf && . $topdir/minipack.conf

get_recipe_name()
{
  name=$recipedir/$1.recipe
  if [ ! -f $name ]; then
    echo >&2 "Recipe for \"$1\" not found."
    exit 1
  fi
  echo $name
}

cmd=$1
shift
tool=$tooldir/mpk-$cmd
if [ -f $tool ]; then
  . $tool "$@"
else
  echo $prog: Invalid command: $cmd
fi

